// <auto-generated />
using System;
using AppointmentCrm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppointmentCrm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppointmentCrmDbContext))]
    [Migration("20260821181711_BindSessionToMembershipUser")]
    partial class BindSessionToMembershipUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.PermissionDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "tenant.read",
                            Name = "tenant.read"
                        },
                        new
                        {
                            Code = "tenant.switch",
                            Name = "tenant.switch"
                        },
                        new
                        {
                            Code = "memberships.read",
                            Name = "memberships.read"
                        },
                        new
                        {
                            Code = "memberships.manage",
                            Name = "memberships.manage"
                        },
                        new
                        {
                            Code = "sessions.manage-own",
                            Name = "sessions.manage-own"
                        },
                        new
                        {
                            Code = "customers.manage",
                            Name = "customers.manage"
                        },
                        new
                        {
                            Code = "appointments.manage",
                            Name = "appointments.manage"
                        },
                        new
                        {
                            Code = "appointments.read-own",
                            Name = "appointments.read-own"
                        },
                        new
                        {
                            Code = "reporting.read",
                            Name = "reporting.read"
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.RoleDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Owner",
                            Name = "Owner"
                        },
                        new
                        {
                            Code = "Manager",
                            Name = "Manager"
                        },
                        new
                        {
                            Code = "Receptionist",
                            Name = "Receptionist"
                        },
                        new
                        {
                            Code = "Employee",
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.RolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role_code");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleCode", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "tenant.read"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "tenant.switch"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "memberships.read"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "memberships.manage"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "sessions.manage-own"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "customers.manage"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "appointments.manage"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "appointments.read-own"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "reporting.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "tenant.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "tenant.switch"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "memberships.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "sessions.manage-own"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "customers.manage"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "appointments.manage"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "reporting.read"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "tenant.read"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "tenant.switch"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "sessions.manage-own"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "customers.manage"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "appointments.manage"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "tenant.read"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "tenant.switch"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "sessions.manage-own"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "appointments.read-own"
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuthorizationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("authorization_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "Role")
                        .HasDatabaseName("ix_tenant_memberships_tenant_role");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_memberships_tenant_user");

                    b.ToTable("tenant_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_memberships_role", "role IN ('Owner', 'Manager', 'Receptionist', 'Employee')");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("security_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_user_sessions_token_hash");

                    b.HasIndex("FamilyId", "RevokedAtUtc")
                        .HasDatabaseName("ix_user_sessions_family_active");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("ix_user_sessions_user_active");

                    b.HasIndex("TenantId", "MembershipId", "UserId");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Identity.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.TenantMembership", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Identity.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.UserSession", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Identity.TenantMembership", "Membership")
                        .WithMany("Sessions")
                        .HasForeignKey("TenantId", "MembershipId", "UserId")
                        .HasPrincipalKey("TenantId", "Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.Tenant", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.TenantMembership", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.User", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
