// <auto-generated />
using System;
using AppointmentCrm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppointmentCrm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppointmentCrmDbContext))]
    [Migration("20260823001133_AppointmentLifecycle")]
    partial class AppointmentLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppointmentCrm.Domain.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("ServiceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("service_currency");

                    b.Property<int>("ServiceDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("service_duration_minutes");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("service_name");

                    b.Property<decimal>("ServicePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("service_price");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ServiceId");

                    b.HasIndex("TenantId", "CustomerId", "StartsAtUtc")
                        .HasDatabaseName("ix_appointments_tenant_customer_start");

                    b.HasIndex("TenantId", "EmployeeId", "StartsAtUtc")
                        .HasDatabaseName("ix_appointments_tenant_employee_start");

                    b.HasIndex("TenantId", "Status", "StartsAtUtc")
                        .HasDatabaseName("ix_appointments_tenant_status_start");

                    b.ToTable("appointments", null, t =>
                        {
                            t.HasCheckConstraint("ck_appointments_range", "starts_at_utc < ends_at_utc");

                            t.HasCheckConstraint("ck_appointments_revision", "revision > 0");

                            t.HasCheckConstraint("ck_appointments_snapshot_currency", "service_currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_appointments_snapshot_duration", "service_duration_minutes BETWEEN 5 AND 480 AND service_duration_minutes % 5 = 0");

                            t.HasCheckConstraint("ck_appointments_snapshot_price", "service_price >= 0 AND service_price <= 1000000");

                            t.HasCheckConstraint("ck_appointments_status", "status IN ('Scheduled', 'Confirmed', 'Completed', 'Cancelled', 'NoShow')");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Appointments.AppointmentStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("from_status");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ActorMembershipId", "ActorUserId");

                    b.HasIndex("TenantId", "AppointmentId", "OccurredAtUtc")
                        .HasDatabaseName("ix_appointment_status_history_timeline");

                    b.ToTable("appointment_status_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_appointment_status_history_from_status", "from_status IS NULL OR from_status IN ('Scheduled', 'Confirmed', 'Completed', 'Cancelled', 'NoShow')");

                            t.HasCheckConstraint("ck_appointment_status_history_to_status", "to_status IN ('Scheduled', 'Confirmed', 'Completed', 'Cancelled', 'NoShow')");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_entries_tenant_occurred");

                    b.HasIndex("TenantId", "ActorMembershipId", "ActorUserId");

                    b.HasIndex("TenantId", "TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_entries_tenant_target");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("NormalizedPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_tenant_email")
                        .HasFilter("normalized_email IS NOT NULL");

                    b.HasIndex("TenantId", "NormalizedPhone")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_tenant_phone")
                        .HasFilter("normalized_phone IS NOT NULL");

                    b.HasIndex("TenantId", "ArchivedAtUtc", "NormalizedName")
                        .HasDatabaseName("ix_customers_tenant_active_name");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.PermissionDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "tenant.read",
                            Name = "tenant.read"
                        },
                        new
                        {
                            Code = "tenant.switch",
                            Name = "tenant.switch"
                        },
                        new
                        {
                            Code = "memberships.read",
                            Name = "memberships.read"
                        },
                        new
                        {
                            Code = "memberships.manage",
                            Name = "memberships.manage"
                        },
                        new
                        {
                            Code = "sessions.manage-own",
                            Name = "sessions.manage-own"
                        },
                        new
                        {
                            Code = "customers.read",
                            Name = "customers.read"
                        },
                        new
                        {
                            Code = "customers.manage",
                            Name = "customers.manage"
                        },
                        new
                        {
                            Code = "services.read",
                            Name = "services.read"
                        },
                        new
                        {
                            Code = "services.manage",
                            Name = "services.manage"
                        },
                        new
                        {
                            Code = "employees.read",
                            Name = "employees.read"
                        },
                        new
                        {
                            Code = "employees.manage",
                            Name = "employees.manage"
                        },
                        new
                        {
                            Code = "scheduling.manage",
                            Name = "scheduling.manage"
                        },
                        new
                        {
                            Code = "availability.read",
                            Name = "availability.read"
                        },
                        new
                        {
                            Code = "appointments.read",
                            Name = "appointments.read"
                        },
                        new
                        {
                            Code = "appointments.manage",
                            Name = "appointments.manage"
                        },
                        new
                        {
                            Code = "appointments.read-own",
                            Name = "appointments.read-own"
                        },
                        new
                        {
                            Code = "appointments.transition-own",
                            Name = "appointments.transition-own"
                        },
                        new
                        {
                            Code = "reporting.read",
                            Name = "reporting.read"
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.RoleDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Owner",
                            Name = "Owner"
                        },
                        new
                        {
                            Code = "Manager",
                            Name = "Manager"
                        },
                        new
                        {
                            Code = "Receptionist",
                            Name = "Receptionist"
                        },
                        new
                        {
                            Code = "Employee",
                            Name = "Employee"
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.RolePermission", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role_code");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("permission_code");

                    b.HasKey("RoleCode", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "tenant.read"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "tenant.switch"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "memberships.read"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "memberships.manage"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "sessions.manage-own"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "customers.read"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "customers.manage"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "services.read"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "services.manage"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "employees.read"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "employees.manage"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "scheduling.manage"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "availability.read"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "appointments.read"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "appointments.manage"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "appointments.read-own"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "appointments.transition-own"
                        },
                        new
                        {
                            RoleCode = "Owner",
                            PermissionCode = "reporting.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "tenant.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "tenant.switch"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "memberships.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "sessions.manage-own"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "customers.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "customers.manage"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "services.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "services.manage"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "employees.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "employees.manage"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "scheduling.manage"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "availability.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "appointments.read"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "appointments.manage"
                        },
                        new
                        {
                            RoleCode = "Manager",
                            PermissionCode = "reporting.read"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "tenant.read"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "tenant.switch"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "sessions.manage-own"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "customers.read"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "customers.manage"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "services.read"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "employees.read"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "availability.read"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "appointments.read"
                        },
                        new
                        {
                            RoleCode = "Receptionist",
                            PermissionCode = "appointments.manage"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "tenant.read"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "tenant.switch"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "sessions.manage-own"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "services.read"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "availability.read"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "appointments.read-own"
                        },
                        new
                        {
                            RoleCode = "Employee",
                            PermissionCode = "appointments.transition-own"
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AuthorizationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("authorization_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "UserId")
                        .HasName("ak_tenant_memberships_tenant_user");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "Role")
                        .HasDatabaseName("ix_tenant_memberships_tenant_role");

                    b.ToTable("tenant_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_memberships_role", "role IN ('Owner', 'Manager', 'Receptionist', 'Employee')");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("SecurityVersion")
                        .HasColumnType("integer")
                        .HasColumnName("security_version");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_user_sessions_token_hash");

                    b.HasIndex("FamilyId", "RevokedAtUtc")
                        .HasDatabaseName("ix_user_sessions_family_active");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("ix_user_sessions_user_active");

                    b.HasIndex("TenantId", "MembershipId", "UserId");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_messages_pending");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId")
                        .HasDatabaseName("ix_outbox_messages_tenant_aggregate");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_attempts", "attempts >= 0");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.DateScheduleOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ux_date_overrides_tenant_date")
                        .HasFilter("employee_id IS NULL");

                    b.HasIndex("TenantId", "EmployeeId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ux_date_overrides_employee_date")
                        .HasFilter("employee_id IS NOT NULL");

                    b.ToTable("date_schedule_overrides", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.DateScheduleOverridePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EndMinute")
                        .HasColumnType("integer")
                        .HasColumnName("end_minute");

                    b.Property<Guid>("OverrideId")
                        .HasColumnType("uuid")
                        .HasColumnName("override_id");

                    b.Property<int>("StartMinute")
                        .HasColumnType("integer")
                        .HasColumnName("start_minute");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OverrideId", "StartMinute")
                        .HasDatabaseName("ix_date_override_periods_lookup");

                    b.ToTable("date_schedule_override_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_date_override_periods_minutes", "start_minute >= 0 AND end_minute <= 1440 AND start_minute < end_minute AND start_minute % 5 = 0 AND end_minute % 5 = 0");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.EmployeeTimeOff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeId", "StartUtc", "EndUtc")
                        .HasDatabaseName("ix_employee_time_offs_overlap");

                    b.ToTable("employee_time_offs", null, t =>
                        {
                            t.HasCheckConstraint("ck_employee_time_offs_range", "start_utc < end_utc");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.WeeklySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_weekly_schedules_tenant_default")
                        .HasFilter("employee_id IS NULL");

                    b.HasIndex("TenantId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_weekly_schedules_tenant_employee")
                        .HasFilter("employee_id IS NOT NULL");

                    b.ToTable("weekly_schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_weekly_schedules_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.WeeklyScheduleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_note");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("mode");

                    b.Property<Guid?>("RestoredFromVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("restored_from_version_id");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<long>("VersionNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ActorMembershipId", "ActorUserId");

                    b.HasIndex("TenantId", "ScheduleId", "CreatedAtUtc")
                        .HasDatabaseName("ix_weekly_schedule_versions_history");

                    b.HasIndex("TenantId", "ScheduleId", "RestoredFromVersionId");

                    b.HasIndex("TenantId", "ScheduleId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_weekly_schedule_versions_schedule_number");

                    b.ToTable("weekly_schedule_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_weekly_schedule_versions_mode", "mode IN ('Custom', 'Closed', 'Inherited')");

                            t.HasCheckConstraint("ck_weekly_schedule_versions_number", "version_number > 0");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.WeeklyScheduleVersionPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<int>("EndMinute")
                        .HasColumnType("integer")
                        .HasColumnName("end_minute");

                    b.Property<int>("StartMinute")
                        .HasColumnType("integer")
                        .HasColumnName("start_minute");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "VersionId", "DayOfWeek", "StartMinute")
                        .HasDatabaseName("ix_weekly_schedule_version_periods_lookup");

                    b.ToTable("weekly_schedule_version_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_weekly_schedule_version_periods_day", "day_of_week BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_weekly_schedule_version_periods_minutes", "start_minute >= 0 AND end_minute <= 1440 AND start_minute < end_minute AND start_minute % 5 = 0 AND end_minute % 5 = 0");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Services.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("NormalizedPhone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("normalized_phone");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_employees_tenant_user")
                        .HasFilter("user_id IS NOT NULL");

                    b.HasIndex("TenantId", "IsActive", "NormalizedName")
                        .HasDatabaseName("ix_employees_tenant_active_name");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Services.EmployeeService", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.HasKey("TenantId", "EmployeeId", "ServiceId");

                    b.HasIndex("TenantId", "ServiceId")
                        .HasDatabaseName("ix_employee_services_tenant_service");

                    b.ToTable("employee_services", (string)null);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Services.ServiceOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("normalized_name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_services_tenant_name");

                    b.HasIndex("TenantId", "IsActive", "NormalizedName")
                        .HasDatabaseName("ix_services_tenant_active_name");

                    b.ToTable("services", null, t =>
                        {
                            t.HasCheckConstraint("ck_services_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_services_duration", "duration_minutes BETWEEN 5 AND 480 AND duration_minutes % 5 = 0");

                            t.HasCheckConstraint("ck_services_price", "price >= 0 AND price <= 1000000");
                        });
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Appointments.Appointment", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Services.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("TenantId", "EmployeeId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Services.ServiceOffering", "Service")
                        .WithMany()
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Appointments.AppointmentStatusHistory", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Appointments.Appointment", "Appointment")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TenantId", "AppointmentId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Identity.TenantMembership", "ActorMembership")
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorMembershipId", "ActorUserId")
                        .HasPrincipalKey("TenantId", "Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActorMembership");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Auditing.AuditEntry", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorMembershipId", "ActorUserId")
                        .HasPrincipalKey("TenantId", "Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Customers.Customer", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.PermissionDefinition", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Identity.RoleDefinition", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.TenantMembership", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Identity.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.UserSession", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Identity.TenantMembership", "Membership")
                        .WithMany("Sessions")
                        .HasForeignKey("TenantId", "MembershipId", "UserId")
                        .HasPrincipalKey("TenantId", "Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Outbox.OutboxMessage", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.DateScheduleOverride", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Services.Employee", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EmployeeId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.DateScheduleOverridePeriod", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Scheduling.DateScheduleOverride", "Override")
                        .WithMany("Periods")
                        .HasForeignKey("TenantId", "OverrideId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Override");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.EmployeeTimeOff", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Services.Employee", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EmployeeId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.WeeklySchedule", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Services.Employee", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "EmployeeId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.WeeklyScheduleVersion", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Scheduling.WeeklySchedule", "Schedule")
                        .WithMany("Versions")
                        .HasForeignKey("TenantId", "ScheduleId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Identity.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorMembershipId", "ActorUserId")
                        .HasPrincipalKey("TenantId", "Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AppointmentCrm.Domain.Scheduling.WeeklyScheduleVersion", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ScheduleId", "RestoredFromVersionId")
                        .HasPrincipalKey("TenantId", "ScheduleId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.WeeklyScheduleVersionPeriod", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Scheduling.WeeklyScheduleVersion", "Version")
                        .WithMany("Periods")
                        .HasForeignKey("TenantId", "VersionId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Services.Employee", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Identity.TenantMembership", "Membership")
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .HasPrincipalKey("TenantId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Services.EmployeeService", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Services.Employee", "Employee")
                        .WithMany("ServiceAssignments")
                        .HasForeignKey("TenantId", "EmployeeId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppointmentCrm.Domain.Services.ServiceOffering", "Service")
                        .WithMany("EmployeeAssignments")
                        .HasForeignKey("TenantId", "ServiceId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Services.ServiceOffering", b =>
                {
                    b.HasOne("AppointmentCrm.Domain.Identity.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Appointments.Appointment", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.Tenant", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.TenantMembership", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Identity.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.DateScheduleOverride", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.WeeklySchedule", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Scheduling.WeeklyScheduleVersion", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Services.Employee", b =>
                {
                    b.Navigation("ServiceAssignments");
                });

            modelBuilder.Entity("AppointmentCrm.Domain.Services.ServiceOffering", b =>
                {
                    b.Navigation("EmployeeAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
